import {
  AmericanEspresso,
  Capuccino,
  CoffeeWithMilk,
  CreamyEspresso,
  IcedEspresso,
  Latte,
  TraditionalEspresso,
  Macchiato,
  Moccacino,
  HotChocolate,
  Cuban,
  Hawaiian,
  Arabic,
  Irish,
} from '../ui/images'

export const coffeeCards = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    types: ['TRADICIONAL'],
    price: 9.9,
    componentSvg: TraditionalEspresso,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    types: ['TRADICIONAL'],
    price: 9.9,
    componentSvg: AmericanEspresso,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    types: ['TRADICIONAL'],
    price: 9.9,
    componentSvg: CreamyEspresso,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    types: ['TRADICIONAL', 'GELADO'],
    price: 9.9,
    componentSvg: IcedEspresso,
  },
  {
    id: 5,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: CoffeeWithMilk,
  },
  {
    id: 6,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: Latte,
  },
  {
    id: 7,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: Capuccino,
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: Macchiato,
  },
  {
    id: 9,
    name: 'Moccacino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    types: ['TRADICIONAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: Moccacino,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    types: ['ESPECIAL', 'COM LEITE'],
    price: 9.9,
    componentSvg: HotChocolate,
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    types: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    price: 9.9,
    componentSvg: Cuban,
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    types: ['ESPECIAL'],
    price: 9.9,
    componentSvg: Hawaiian,
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    types: ['ESPECIAL'],
    price: 9.9,
    componentSvg: Arabic,
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    types: ['ESPECIAL', 'ALCOÓLICO'],
    price: 9.9,
    componentSvg: Irish,
  },
]
